"""AI watermark / provenance marker detection.

Scans an image file for traces that AI generators routinely leave behind:

  1. C2PA / Content Credentials (DALL-E 3, Adobe Firefly, Microsoft Designer
     etc. embed a JUMBF-wrapped manifest in the file).
  2. PNG iTXt/tEXt chunks with the names "parameters", "prompt", "workflow",
     "Comment" — Automatic1111 / ComfyUI / InvokeAI all write the prompt and
     model details here.
  3. EXIF / XMP fields containing AI-generator vendor strings.
  4. Substring sweep over the raw file bytes for known generator names.
  5. A spectral-anomaly check at the DWT mid-band where most published
     spread-spectrum watermarks (incl. the Stable-Diffusion default
     `invisible-watermark` library) place their payload.
  6. JPEG quantization-table fingerprinting: cameras use manufacturer-
     specific QTs; AI tools saving JPEGs through Pillow / libjpeg leave
     the well-known reference tables, which are detectable.

This module finds *visible* (i.e. detectable-without-the-secret) markers.
True secret watermarks like Google SynthID are designed to be undetectable
without the publisher's verification key — those cannot be read by any
classical method, so we only flag SynthID *if its name appears in the
metadata*, which it sometimes does.
"""

from __future__ import annotations

import io as _io
from pathlib import Path

import numpy as np
from PIL import ExifTags, Image

from detector import _grayscale, _haar_dwt

# Lower-cased substrings to grep for in raw file bytes and metadata strings.
AI_KEYWORDS = (
    # Generator vendors
    "stable-diffusion", "stable diffusion", "stablediffusion",
    "midjourney", "openai", "dall-e", "dalle",
    "adobe firefly", "firefly",
    "automatic1111", "a1111", "comfyui", "invokeai", "novelai",
    "sdxl", "flux", "playgroundai", "leonardo.ai", "ideogram", "recraft",
    "gpt-image", "imagen", "gemini",
    # Watermark / provenance schemes
    "c2pa", "contentcredentials", "content credentials", "synthid",
    "jumbf", "stegastamp",
    # Common SD prompt/parameter field signatures
    "negative prompt:", "steps:", "sampler:", "cfg scale:",
    "model hash:", "denoising strength:",
    # Tool tags
    "made with ai", "generated by ai", "ai-generated",
)

#: PNG text chunks whose mere *presence* is generator evidence: nothing but a
#: diffusion UI writes a chunk called "parameters" or "workflow".
PNG_GENERATOR_CHUNKS = {"parameters", "prompt", "workflow", "negative_prompt"}

#: PNG text chunks that ordinary editors write too ("Software: GIMP 2.10").
#: Their presence proves nothing; only AI content inside them counts.
PNG_GENERIC_CHUNKS = {"comment", "description", "software", "metadata"}

PNG_AI_CHUNK_NAMES = PNG_GENERATOR_CHUNKS | PNG_GENERIC_CHUNKS


def _bytes_search(raw: bytes, needles: tuple[str, ...]) -> list[str]:
    low = raw.lower()
    found = []
    for n in needles:
        if n.encode("utf-8", errors="ignore") in low:
            found.append(n)
    return found


def metadata_bytes(raw: bytes) -> bytes:
    """The parts of a file that can legitimately carry text, entropy data excluded.

    Sweeping *whole* file bytes for generator names is a false-positive machine:
    a 4 MB JPEG entropy stream is effectively random, and short needles like
    ``a1111`` or ``flux`` turn up in it by chance (measured on a 160-photograph
    corpus: 1 spurious hit). Provenance strings can only live in the metadata
    segments, so that is all this returns:

      * JPEG - the APPn (0xE0-0xEF) and COM (0xFE) marker segments, stopping at
        the start-of-scan marker after which everything is compressed data.
      * PNG  - every chunk except IDAT (the compressed image itself).
      * anything else - the whole buffer, which is the previous behaviour; the
        formats that reach this branch (WebP/AVIF/HEIC) store metadata in boxes
        this function does not parse, and missing a real hit is worse than the
        occasional chance one.
    """
    if raw[:2] == b"\xff\xd8":                       # JPEG
        out, i, n = bytearray(), 2, len(raw)
        while i + 4 <= n and raw[i] == 0xFF:
            marker = raw[i + 1]
            if marker in (0xD8, 0x01) or 0xD0 <= marker <= 0xD7:
                i += 2
                continue
            if marker == 0xDA:                       # start of scan
                break
            seg_len = int.from_bytes(raw[i + 2:i + 4], "big")
            if seg_len < 2:
                break
            if 0xE0 <= marker <= 0xEF or marker == 0xFE:
                out += raw[i + 4:i + 2 + seg_len]
            i += 2 + seg_len
        return bytes(out)
    if raw[:8] == b"\x89PNG\r\n\x1a\n":              # PNG
        out, i, n = bytearray(), 8, len(raw)
        while i + 8 <= n:
            length = int.from_bytes(raw[i:i + 4], "big")
            ctype = raw[i + 4:i + 8]
            if ctype != b"IDAT":
                out += ctype + raw[i + 8:i + 8 + length]
            if ctype == b"IEND":
                break
            i += 12 + length                          # len + type + data + crc
        return bytes(out)
    return raw


def _exif_strings(img: Image.Image) -> dict[str, str]:
    out: dict[str, str] = {}
    try:
        exif = img.getexif()
    except Exception:
        return out
    for tag_id, value in exif.items():
        name = ExifTags.TAGS.get(tag_id, str(tag_id))
        if isinstance(value, bytes):
            try:
                value = value.decode("utf-8", errors="replace")
            except Exception:
                continue
        if isinstance(value, str) and value.strip():
            out[name] = value.strip()
    return out


#: Mid-band kurtosis at which this heuristic starts to report anything, and the
#: value at which it saturates. **Measured, not assumed**: over the 160
#: photographs `fetch_corpus.py` downloads (320 LH/HL bands) the distribution is
#: p50 6.1, p75 10.9, p90 23.2, p95 36.9, p99 82.4, max 133.8. The original code
#: assumed "natural images are 3-8" and reported an anomaly above 8 - which is
#: true of 34% of ordinary photographs, and is why 21 of those 160 photographs
#: were being declared watermarked. The knee sits at the measured p95 of real
#: photographs and saturation just past the observed maximum.
KURT_KNEE, KURT_SATURATION = 37.0, 135.0


def _spectral_watermark_anomaly(img: Image.Image) -> float:
    """Mid-band DWT energy concentration check.

    Public spread-spectrum watermarking schemes (incl. the SD default
    DWT-DCT-SVD library) embed bits by perturbing mid-frequency DWT
    coefficients in a structured way. Without the secret key we can't
    recover the bits, but a *strong* perturbation often shows as anomalous
    energy concentration at specific DWT locations.

    Heuristic: take the HL/LH bands, compute their DCT, and measure how
    peaked the mid-frequency energy distribution is (kurtosis of magnitudes
    in the mid annulus). Higher = more peaked = more watermark-suspicious.

    This is *circumstantial* evidence and is scored as such: heavily textured
    photographs reach high mid-band kurtosis with no watermark anywhere near
    them, so on its own this can never trigger a provenance verdict - see
    :func:`inspect`.
    """
    g = _grayscale(img)
    if min(g.shape) < 64:
        return 0.0
    _, lh, hl, _ = _haar_dwt(g)
    score = 0.0
    for band in (lh, hl):
        # 2D FFT magnitude (cheaper proxy for DCT energy distribution)
        f = np.abs(np.fft.fftshift(np.fft.fft2(band)))
        h, w = f.shape
        cy, cx = h // 2, w // 2
        y, x = np.indices(f.shape)
        r = np.hypot(x - cx, y - cy)
        rmax = r.max()
        # Mid annulus: 0.25 - 0.55 of max radius
        mask = (r >= 0.25 * rmax) & (r <= 0.55 * rmax)
        mid = f[mask]
        if mid.size < 10:
            continue
        m = mid - mid.mean()
        std = m.std() + 1e-8
        kurt = (m ** 4).mean() / std ** 4
        score += np.clip((kurt - KURT_KNEE) / (KURT_SATURATION - KURT_KNEE), 0.0, 1.0)
    return float(np.clip(score / 2.0, 0.0, 1.0))


def _qt_signature(qt_dict) -> tuple | None:
    if not qt_dict:
        return None
    return tuple(sorted((k, tuple(v)) for k, v in qt_dict.items()))


_PILLOW_QT_CACHE: dict[int, tuple] | None = None


def _pillow_default_qts() -> dict[int, tuple]:
    global _PILLOW_QT_CACHE
    if _PILLOW_QT_CACHE is not None:
        return _PILLOW_QT_CACHE
    refs = {}
    blank = Image.new("RGB", (16, 16), (128, 128, 128))
    for q in range(50, 101, 5):
        buf = _io.BytesIO()
        blank.save(buf, "JPEG", quality=q)
        buf.seek(0)
        refs[q] = _qt_signature(Image.open(buf).quantization)
    _PILLOW_QT_CACHE = refs
    return refs


def jpeg_qt_fingerprint(path: str | Path) -> dict:
    """Detect JPEGs whose quantization tables match Pillow / libjpeg defaults.

    Camera firmware saves JPEGs with manufacturer-specific quantization
    tables — Apple, Canon, Nikon, Sony each have their own. AI tools that
    save JPEGs in Python through Pillow (or via libjpeg defaults) leave
    one of a small set of well-known reference tables. Matching the input's
    QTs against the Pillow defaults at common qualities (50, 55, ..., 100)
    is a strong "saved by Python" indicator.
    """
    try:
        img = Image.open(path)
        if img.format != "JPEG":
            return {"matched": False, "score": 0.0, "reason": "not a JPEG"}
        sig = _qt_signature(img.quantization)
        if sig is None:
            return {"matched": False, "score": 0.0, "reason": "no QT extracted"}
    except Exception as e:
        return {"matched": False, "score": 0.0, "reason": f"error: {e}"}

    for q, ref in _pillow_default_qts().items():
        if sig == ref:
            return {
                "matched": True,
                "pillow_quality": q,
                "score": 0.7,
                "reason": f"matches Pillow / libjpeg default QT at quality {q}",
            }
    return {"matched": False, "score": 0.0, "reason": "custom or camera-specific QT"}


def inspect(path: str | Path) -> dict:
    """Inspect a file for AI watermarks / provenance markers.

    Evidence is split into two classes, and the distinction is the whole point:

    * **provenance** - a marker somebody deliberately wrote: a C2PA manifest, a
      diffusion UI's PNG parameter chunk, an EXIF field naming a generator, a
      generator name in a metadata segment. This is *decodable* evidence, and
      only this is allowed to override the pixel verdict
      (:func:`pipeline.final_verdict`).
    * **circumstantial** - statistical hints: mid-band spectral anomaly, JPEG
      quantization tables matching the libjpeg defaults. Both fire on perfectly
      ordinary photographs (every image re-saved through any Python pipeline
      matches those tables), so they raise the score without ever, on their own,
      asserting that a watermark exists.

    Returns::

      {
        'c2pa':             bool,
        'png_ai_chunks':    {chunk_name: snippet, ...},
        'exif_ai_fields':   {tag: snippet, ...},
        'keyword_hits':     [matched substring, ...],   # metadata segments only
        'spectral_anomaly': float in [0, 1],
        'jpeg_qt':          {...},
        'provenance':       bool,        # hard evidence present
        'evidence':         [human-readable reason, ...],
        'score':            float in [0, 1],
        'verdict':          str,
      }
    """
    path = Path(path)
    raw = path.read_bytes()[:4_000_000]  # cap at 4 MB for performance

    # Only the metadata segments: the compressed image data cannot carry a
    # provenance string, but it can and does contain one by chance.
    meta = metadata_bytes(raw)
    keyword_hits = _bytes_search(meta, AI_KEYWORDS)
    low = meta.lower()
    c2pa = b"jumbf" in low or b"c2pa" in low or b"contentcredentials" in low

    png_ai_chunks: dict[str, str] = {}
    generator_chunks: list[str] = []
    exif_ai_fields: dict[str, str] = {}
    spectral_anomaly = 0.0
    try:
        img = Image.open(path)
        if img.format == "PNG":
            for k, v in (img.info or {}).items():
                key = k.lower()
                if key not in PNG_AI_CHUNK_NAMES or not isinstance(v, str) or not v.strip():
                    continue
                ai_content = any(kw in v.lower() for kw in AI_KEYWORDS)
                # "parameters"/"workflow" are written by diffusion UIs and
                # nothing else; "Software"/"Comment" are written by every
                # image editor, so those count only if the text is AI.
                if key in PNG_GENERATOR_CHUNKS or ai_content:
                    png_ai_chunks[k] = v.strip()[:600]
                    generator_chunks.append(k)
        for tag, val in _exif_strings(img).items():
            if any(kw in val.lower() for kw in AI_KEYWORDS):
                exif_ai_fields[tag] = val[:300]
        spectral_anomaly = _spectral_watermark_anomaly(img)
    except Exception:
        pass

    qt_check = jpeg_qt_fingerprint(path)

    # -- hard provenance evidence ------------------------------------------- #
    evidence: list[str] = []
    score = 0.0
    if c2pa:
        score += 0.7
        evidence.append("C2PA / Content Credentials manifest")
    if png_ai_chunks:
        score += 0.6
        evidence.append("PNG generation-parameter chunk: "
                        + ", ".join(sorted(generator_chunks)))
    if exif_ai_fields:
        score += 0.4
        evidence.append("EXIF field naming a generator: "
                        + ", ".join(sorted(exif_ai_fields)))
    if keyword_hits:
        score += min(0.4, 0.08 * len(keyword_hits))
        evidence.append("generator name in a metadata segment: "
                        + ", ".join(sorted(set(keyword_hits))[:6]))

    # -- circumstantial clues ----------------------------------------------- #
    # Capped so that both together (0.25 + 0.15) stay under the 0.5 reporting
    # threshold: no amount of statistical suspicion is a watermark.
    score += 0.25 * spectral_anomaly
    if qt_check["matched"]:
        score += 0.15
    score = float(min(1.0, score))

    provenance = bool(evidence)
    if provenance:
        verdict = "AI provenance detected"
    elif score >= 0.3:
        verdict = "no provenance metadata (circumstantial indicators only)"
    else:
        verdict = "no watermark detected"

    return {
        "c2pa": c2pa,
        "png_ai_chunks": png_ai_chunks,
        "exif_ai_fields": exif_ai_fields,
        "keyword_hits": sorted(set(keyword_hits)),
        "spectral_anomaly": spectral_anomaly,
        "jpeg_qt": qt_check,
        "provenance": provenance,
        "evidence": evidence,
        "score": score,
        "verdict": verdict,
    }
