"""AI watermark / provenance marker detection.

Scans an image file for traces that AI generators routinely leave behind:

  1. C2PA / Content Credentials (DALL-E 3, Adobe Firefly, Microsoft Designer
     etc. embed a JUMBF-wrapped manifest in the file).
  2. PNG iTXt/tEXt chunks with the names "parameters", "prompt", "workflow",
     "Comment" — Automatic1111 / ComfyUI / InvokeAI all write the prompt and
     model details here.
  3. EXIF / XMP fields containing AI-generator vendor strings.
  4. Substring sweep over the raw file bytes for known generator names.
  5. A spectral-anomaly check at the DWT mid-band where most published
     spread-spectrum watermarks (incl. the Stable-Diffusion default
     `invisible-watermark` library) place their payload.
  6. JPEG quantization-table fingerprinting: cameras use manufacturer-
     specific QTs; AI tools saving JPEGs through Pillow / libjpeg leave
     the well-known reference tables, which are detectable.

This module finds *visible* (i.e. detectable-without-the-secret) markers.
True secret watermarks like Google SynthID are designed to be undetectable
without the publisher's verification key — those cannot be read by any
classical method, so we only flag SynthID *if its name appears in the
metadata*, which it sometimes does.
"""

from __future__ import annotations

import io as _io
from pathlib import Path

import numpy as np
from PIL import ExifTags, Image

from detector import _grayscale, _haar_dwt

# Lower-cased substrings to grep for in raw file bytes and metadata strings.
AI_KEYWORDS = (
    # Generator vendors
    "stable-diffusion", "stable diffusion", "stablediffusion",
    "midjourney", "openai", "dall-e", "dalle",
    "adobe firefly", "firefly",
    "automatic1111", "a1111", "comfyui", "invokeai", "novelai",
    "sdxl", "flux", "playgroundai", "leonardo.ai", "ideogram", "recraft",
    "gpt-image", "imagen", "gemini",
    # Watermark / provenance schemes
    "c2pa", "contentcredentials", "content credentials", "synthid",
    "jumbf", "stegastamp",
    # Common SD prompt/parameter field signatures
    "negative prompt:", "steps:", "sampler:", "cfg scale:",
    "model hash:", "denoising strength:",
    # Tool tags
    "made with ai", "generated by ai", "ai-generated",
)

PNG_AI_CHUNK_NAMES = {"parameters", "prompt", "workflow", "comment", "description",
                      "software", "negative_prompt", "metadata"}


def _bytes_search(raw: bytes, needles: tuple[str, ...]) -> list[str]:
    low = raw.lower()
    found = []
    for n in needles:
        if n.encode("utf-8", errors="ignore") in low:
            found.append(n)
    return found


def _exif_strings(img: Image.Image) -> dict[str, str]:
    out: dict[str, str] = {}
    try:
        exif = img.getexif()
    except Exception:
        return out
    for tag_id, value in exif.items():
        name = ExifTags.TAGS.get(tag_id, str(tag_id))
        if isinstance(value, bytes):
            try:
                value = value.decode("utf-8", errors="replace")
            except Exception:
                continue
        if isinstance(value, str) and value.strip():
            out[name] = value.strip()
    return out


def _spectral_watermark_anomaly(img: Image.Image) -> float:
    """Mid-band DWT energy concentration check.

    Public spread-spectrum watermarking schemes (incl. the SD default
    DWT-DCT-SVD library) embed bits by perturbing mid-frequency DWT
    coefficients in a structured way. Without the secret key we can't
    recover the bits, but a *strong* perturbation often shows as anomalous
    energy concentration at specific DWT locations.

    Heuristic: take the HL/LH bands, compute their DCT, and measure how
    peaked the mid-frequency energy distribution is (kurtosis of magnitudes
    in the mid annulus). Higher = more peaked = more watermark-suspicious.
    Returns 0.0-0.3 typical, capped at 1.0.
    """
    g = _grayscale(img)
    if min(g.shape) < 64:
        return 0.0
    _, lh, hl, _ = _haar_dwt(g)
    score = 0.0
    for band in (lh, hl):
        # 2D FFT magnitude (cheaper proxy for DCT energy distribution)
        f = np.abs(np.fft.fftshift(np.fft.fft2(band)))
        h, w = f.shape
        cy, cx = h // 2, w // 2
        y, x = np.indices(f.shape)
        r = np.hypot(x - cx, y - cy)
        rmax = r.max()
        # Mid annulus: 0.25 - 0.55 of max radius
        mask = (r >= 0.25 * rmax) & (r <= 0.55 * rmax)
        mid = f[mask]
        if mid.size < 10:
            continue
        m = mid - mid.mean()
        std = m.std() + 1e-8
        kurt = (m ** 4).mean() / std ** 4
        # Real natural-image mid-band kurtosis is typically 3-8. Strong
        # spread-spectrum watermarks push this much higher.
        score += max(0.0, (kurt - 8.0) / 30.0)
    return float(np.clip(score / 2.0, 0.0, 1.0))


def _qt_signature(qt_dict) -> tuple | None:
    if not qt_dict:
        return None
    return tuple(sorted((k, tuple(v)) for k, v in qt_dict.items()))


_PILLOW_QT_CACHE: dict[int, tuple] | None = None


def _pillow_default_qts() -> dict[int, tuple]:
    global _PILLOW_QT_CACHE
    if _PILLOW_QT_CACHE is not None:
        return _PILLOW_QT_CACHE
    refs = {}
    blank = Image.new("RGB", (16, 16), (128, 128, 128))
    for q in range(50, 101, 5):
        buf = _io.BytesIO()
        blank.save(buf, "JPEG", quality=q)
        buf.seek(0)
        refs[q] = _qt_signature(Image.open(buf).quantization)
    _PILLOW_QT_CACHE = refs
    return refs


def jpeg_qt_fingerprint(path: str | Path) -> dict:
    """Detect JPEGs whose quantization tables match Pillow / libjpeg defaults.

    Camera firmware saves JPEGs with manufacturer-specific quantization
    tables — Apple, Canon, Nikon, Sony each have their own. AI tools that
    save JPEGs in Python through Pillow (or via libjpeg defaults) leave
    one of a small set of well-known reference tables. Matching the input's
    QTs against the Pillow defaults at common qualities (50, 55, ..., 100)
    is a strong "saved by Python" indicator.
    """
    try:
        img = Image.open(path)
        if img.format != "JPEG":
            return {"matched": False, "score": 0.0, "reason": "not a JPEG"}
        sig = _qt_signature(img.quantization)
        if sig is None:
            return {"matched": False, "score": 0.0, "reason": "no QT extracted"}
    except Exception as e:
        return {"matched": False, "score": 0.0, "reason": f"error: {e}"}

    for q, ref in _pillow_default_qts().items():
        if sig == ref:
            return {
                "matched": True,
                "pillow_quality": q,
                "score": 0.7,
                "reason": f"matches Pillow / libjpeg default QT at quality {q}",
            }
    return {"matched": False, "score": 0.0, "reason": "custom or camera-specific QT"}


def inspect(path: str | Path) -> dict:
    """Inspect a file for AI watermarks / provenance markers.

    Returns:
      {
        'c2pa':            bool,
        'png_ai_chunks':   {chunk_name: snippet, ...},
        'exif_ai_fields':  {tag: snippet, ...},
        'keyword_hits':    [matched substring, ...],
        'spectral_anomaly': float in [0, 1],
        'score':           float in [0, 1],   # combined watermark confidence
        'verdict':         'AI watermark detected' | 'no watermark detected',
      }
    """
    path = Path(path)
    raw = path.read_bytes()[:4_000_000]  # cap at 4 MB for performance

    keyword_hits = _bytes_search(raw, AI_KEYWORDS)
    c2pa = b"jumbf" in raw.lower() or b"c2pa" in raw.lower() or b"contentcredentials" in raw.lower()

    png_ai_chunks: dict[str, str] = {}
    exif_ai_fields: dict[str, str] = {}
    spectral_anomaly = 0.0
    try:
        img = Image.open(path)
        if img.format == "PNG":
            for k, v in (img.info or {}).items():
                if k.lower() in PNG_AI_CHUNK_NAMES and isinstance(v, str) and v.strip():
                    png_ai_chunks[k] = v.strip()[:600]
        for tag, val in _exif_strings(img).items():
            if any(kw in val.lower() for kw in AI_KEYWORDS):
                exif_ai_fields[tag] = val[:300]
        spectral_anomaly = _spectral_watermark_anomaly(img)
    except Exception:
        pass

    qt_check = jpeg_qt_fingerprint(path)

    score = 0.0
    if c2pa:
        score += 0.7
    if png_ai_chunks:
        score += 0.6
    if exif_ai_fields:
        score += 0.4
    if keyword_hits:
        score += min(0.4, 0.08 * len(keyword_hits))
    score += 0.5 * spectral_anomaly
    if qt_check["matched"]:
        # Down-weighted: many real photos that have been re-saved through
        # any libjpeg-based pipeline match the same default tables, so this
        # is a contributing clue, not standalone proof.
        score += 0.3
    score = float(min(1.0, score))

    return {
        "c2pa": c2pa,
        "png_ai_chunks": png_ai_chunks,
        "exif_ai_fields": exif_ai_fields,
        "keyword_hits": sorted(set(keyword_hits)),
        "spectral_anomaly": spectral_anomaly,
        "jpeg_qt": qt_check,
        "score": score,
        "verdict": "AI watermark detected" if score >= 0.5 else "no watermark detected",
    }
